name: Run Benchmarks

on:
  workflow_run:
    workflows:
      - Verify Build
    types:
      - completed

jobs:
  run_benchmarks:
    name: Run Benchmarks
    runs-on: ubuntu-latest

    # Only run this job if the workflow run was triggered by a pull request
    if: ${{ github.event.pull_request != null }}

    steps:
      - uses: actions/checkout@v4

      - name: Run Criterion
        uses: boa-dev/criterion-compare-action@v3
        with:
          branchName: ${{ github.event.pull_request.base.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
