name: Run Benchmarks

on:
  workflow_run:
    workflows:
      - Verify Build
    types:
      - completed

jobs:
  run_benchmarks:
    name: Run Benchmarks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run Criterion
        uses: boa-dev/criterion-compare-action@v3
        with:
          branchName: ${{ github.base_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
