name: Verify Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  format:
    name: Code Formatting Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Nightly Rust with rustfmt
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          components: rustfmt

      - name: Run rustfmt
        run: cargo fmt --all -- --check

  build-and-test:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    # Needed for the benchmark workflow to know the base ref
    outputs:
      base_ref: ${{ github.event.pull_request.base.ref }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Set up Cargo Cache
        uses: Swatinem/rust-cache@v2
        with:
          save-if: false

      - name: Run tests
        run: cargo test --workspace --verbose

      - name: Build Release
        run: cargo build --verbose --release
