name: Verify Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  format:
    name: Code Formatting Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Nightly Rust with rustfmt
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          components: rustfmt

      - name: Run rustfmt
        run: cargo fmt --all -- --check

  build-and-test:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-14]

    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Set up Cargo Cache
        uses: Swatinem/rust-cache@v2
        with:
          save-if: false

      - name: Run tests
        run: cargo test --workspace --verbose

      - name: Build Release
        run: cargo build --verbose --release

      # `ark-cli-watch.sh` script tests the functionality of `ark-cli watch`,
      # which monitors a directory for file changes using a filesystem watcher and updates the index file.
      # We need to run it on each platform to ensure it works across all OSes.
      - name: Run `ark-cli watch` test
        run: ./integration/ark-cli-watch.sh

      - name: Upload Release Build
        uses: actions/upload-artifact@v3
        with:
          name: release-build-${{ matrix.os }}
          path: target/release/
